# Ready or Not - Corrected config.toml for Supabase CLI 2.31.8
# A string used to distinguish different Supabase projects on the same host
project_id = "ready-or-not"

[api]
enabled = true
# Use different port from Global Game Loader (54321)
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
# Use different port from Global Game Loader (54322)
port = 54332
shadow_port = 54330
major_version = 17

[db.pooler]
enabled = false
port = 54339
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
# Use different port from Global Game Loader (54323)
port = 54333
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
# Use different port from Global Game Loader (54324)
port = 54334

[auth]
enabled = true
# Site URL for redirects (corrected port for Vite dev server)
site_url = "http://localhost:5173"
# Additional redirect URLs (corrected port)
additional_redirect_urls = [
    "http://localhost:5173/**",
    "http://localhost:5173/dashboard",
    "http://localhost:5173/dashboard/**",
    "https://ready-or-not.pages.dev/**"
]
# JWT settings
jwt_expiry = 3600
# Enable refresh token rotation
enable_refresh_token_rotation = true
# Refresh token reuse interval
refresh_token_reuse_interval = 10

[auth.email]
# Allow/disallow new user signups via email to your project
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = false
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
# If enabled, users will need to reauthenticate or have logged in recently to change their password.
secure_password_change = false
# Controls the minimum amount of time that must pass before sending another signup confirmation or password reset email.
max_frequency = "1s"
# Number of characters used in the email OTP.
otp_length = 6
# Number of seconds before the email OTP expires (defaults to 1 hour).
otp_expiry = 3600

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = false
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending OTP to users
template = "Your code is {{ .Code }}"
# Controls the minimum amount of time that must pass before sending another sms otp.
max_frequency = "5s"

[auth.rate_limit]
# Number of emails that can be sent per hour.
email_sent = 100
# Number of SMS messages that can be sent per hour.
sms_sent = 100
# Number of anonymous sign-ins that can be made per hour per IP address.
anonymous_users = 100
# Number of sessions that can be refreshed in a 5 minute interval per IP address.
token_refresh = 150
# Number of sign up and sign-in requests that can be made in a 5 minute interval per IP address.
sign_in_sign_ups = 100
# Number of OTP / Magic link verifications that can be made in a 5 minute interval per IP address.
token_verifications = 100
# Number of Web3 logins that can be made in a 5 minute interval per IP address.
web3 = 100

[storage]
enabled = false

[analytics]
enabled = true
port = 54337

[edge_runtime]
enabled = true